### ISSUE TITLE
misspelling of tendermint  type

### ISSUE THREAD

**Issue by livelybug** [octopus-network/ibc-rs#97]
After running the command below to establish channels between 2 chains
```
cargo run -- -c hermes.toml create channel ibc-0 earth --port-a transfer --port-b transfer -o unordered
```

The consensus type in the events generated may be of typo.

![image](https://user-images.githubusercontent.com/13627060/142793739-c687f643-1b76-4da0-8152-0a1ff6161fc5.png)

**Comment by DaviRain-Su** [comment]
This should be a problem with this enum type of client-type as defined in polkadpt-js. 
This address: https://octopusnetwork.notion.site/substrate-ibc-test-5173afe03d6844ab99bfc4164c63ca73 
and update enum client-type, This is a misspelling of tendermint.

**Comment by livelybug** [comment]
> This should be a problem with this enum type of client-type as defined in polkadpt-js. This address: https://octopusnetwork.notion.site/substrate-ibc-test-5173afe03d6844ab99bfc4164c63ca73 and update enum client-type, This is a misspelling of tendermint.

No "Tenderming" found on https://octopusnetwork.notion.site/substrate-ibc-test-5173afe03d6844ab99bfc4164c63ca73

**Comment by DaviRain-Su** [comment]
> > This should be a problem with this enum type of client-type as defined in polkadpt-js. This address: https://octopusnetwork.notion.site/substrate-ibc-test-5173afe03d6844ab99bfc4164c63ca73 and update enum client-type, This is a misspelling of tendermint.
> 
> No "Tenderming" found on https://octopusnetwork.notion.site/substrate-ibc-test-5173afe03d6844ab99bfc4164c63ca73

Have been update to Tendermint.
```
"ClientType": {
    "_enum": [
      "Tendermint",
      "Grandpa"
    ]
  },
```
